import{a as u,S as d,i as l}from"./assets/vendor-B3IAfeER.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&s(o)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();function f(a){return u.get("https://pixabay.com/api/",{params:{key:"53489981-68e2194cff91adb725bcb77ca",q:a,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(r=>r.data)}const i={gallery:document.querySelector(".js-gallery"),loader:document.querySelector(".js-loader")};let p=new d(".gallery a",{captionsData:"alt",captionDelay:250});function m({webformatURL:a,largeImageURL:r,tags:n,likes:s,views:e,comments:t,downloads:o}){return`
    <li class = "gallery-item">
        <a href="${r}">
            <img src="${a}" alt="${n}" loading="lazy" />
        </a>
        <div class="card-info">
            <div class="headers"><span>Likes</span><span>Views</span><span>Comments</span><span>Downloads</span></div>
            <div class="values"><span>${s}</span><span>${e}</span><span>${t}</span><span>${o}</span></div>
        </div>
    </li>`}function y(a){return a.map(m).join("")}function g(a){const r=y(a);i.gallery.insertAdjacentHTML("beforeend",r),p.refresh()}function h(){i.gallery.innerHTML=""}function L(){i.loader.classList.remove("hidden")}function v(){i.loader.classList.add("hidden")}const c={form:document.querySelector(".js-pixabay-form"),input:document.querySelector("input[name='search-text']")};c.form.addEventListener("submit",a=>{a.preventDefault();const r=a.target.elements["search-text"].value.trim();if(!r){l.show({title:"Hey",message:"Please enter a search query!"});return}h(),L(),f(r).then(function(n){if(n.hits.length===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}const s=n.hits;g(s)}).catch(function(n){l.error({message:"Something went wrong. Try again later!",position:"topRight"})}).finally(function(){v()}),c.form.reset()});
//# sourceMappingURL=index.js.map
